version: 5.2.0.{build}.{branch}
environment:
  access_token:
    secure: vsDaeFdGCIGlIxWSEdsDomYtr5mKS5IPGHc4NwuDZ5D6mCna0STrDvMZ6IP6mOBK
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - 5_1-new
  - master
skip_tags: true
os: Visual Studio 2013
configuration: Release
shallow_clone: false
clone_depth: 1
clone_folder: C:\Repos\wolfmania
init:
- cmd: >-
    git config --global credential.helper store

    set APPVEYOR_BUILD_URL=https://ci.appveyor.com/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/build/%APPVEYOR_BUILD_VERSION%

    set SM_COMMIT_SHORT=%APPVEYOR_REPO_COMMIT:~0,7%
install:
- cmd: >-
    git submodule init

    git submodule update extern/cppformat

    git submodule update extern/tommath

    git submodule update extern/tomcrypt

    git submodule update extern/googletest

    choco install cmake -y

    choco install nsis -y -version 2.46.0.20150406
build_script:
- cmd: >-
    echo Running cmake now...

    cd "C:\Repos\wolfmania\Build"

    "C:\Program Files\CMake\bin\cmake" -G "Visual Studio 12 2013" -T "v120_xp" -DWITH_IRC_POST_HOOK=ON ..
    
    msbuild "C:\Repos\wolfmania\Build\StepMania.sln" /maxcpucount:4 /verbosity:normal
    
    msbuild "C:\Repos\wolfmania\Build\PACKAGE.vcxproj" /maxcpucount:4 /verbosity:minimal
artifacts:
  - path: Build/*.exe
    type: exe
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: vsDaeFdGCIGlIxWSEdsDomYtr5mKS5IPGHc4NwuDZ5D6mCna0STrDvMZ6IP6mOBK
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_success:
- cmd: >-
    echo "Posting to IRC now..."

    #C:\Repos\wolfmania\Program\irc-reporter.exe "%APPVEYOR_REPO_NAME%" "%APPVEYOR_BUILD_VERSION%"  "%SM_COMMIT_SHORT%" "%APPVEYOR_REPO_COMMIT_AUTHOR%" "%APPVEYOR_BUILD_URL%" "success"
on_failure:
- cmd: >-
    echo "Posting to IRC now..."

    #C:\Repos\wolfmania\Program\irc-reporter.exe "%APPVEYOR_REPO_NAME%" "%APPVEYOR_BUILD_VERSION%" "%SM_COMMIT_SHORT%" "%APPVEYOR_REPO_COMMIT_AUTHOR%" "%APPVEYOR_BUILD_URL%" "failure"
